---
detectors:
  InstanceVariableAssumption:
    exclude:
      - RubyCritic::Analyser::Coverage
  IrresponsibleModule:
    exclude:
    - RubyCritic::Analyser::Attributes
    - RubyCritic::Analyser::Churn
    - RubyCritic::Analyser::Complexity
    - Parser::AST::Node
    - RubyCritic::AST::EmptyNode
    - RubyCritic::Flay
    - RubyCritic::Flog
    - RubyCritic::MethodsCounter
    - RubyCritic::ModulesLocator
    - RubyCritic::Parser
    - RubyCritic::Reek
    - RubyCritic::Analyser::FlaySmells
    - RubyCritic::Analyser::FlogSmells
    - RubyCritic::Analyser::ReekSmells
    - RubyCritic::AnalysersRunner
    - RubyCritic::Browser
    - RubyCritic::Cli::Application
    - RubyCritic::Cli::Options
    - RubyCritic::Colorize
    - RubyCritic::CommandFactory
    - RubyCritic::Command::Base
    - RubyCritic::Command::Ci
    - RubyCritic::Command::Default
    - RubyCritic::Command::Help
    - RubyCritic::Command::StatusReporter
    - RubyCritic::Command::Version
    - RubyCritic::Config
    - RubyCritic::Configuration
    - RubyCritic::AnalysedModule
    - RubyCritic::AnalysedModulesCollection
    - RubyCritic::Location
    - RubyCritic::Rating
    - RubyCritic::Smell
    - RubyCritic::Generator::ConsoleReport
    - RubyCritic::Generator::Html::Base
    - RubyCritic::Generator::Html::CodeFile
    - RubyCritic::Generator::Html::CodeIndex
    - RubyCritic::Generator::Html::Line
    - RubyCritic::Generator::Html::Overview
    - RubyCritic::Generator::Html::SmellsIndex
    - RubyCritic::Turbulence
    - RubyCritic::ViewHelpers
    - RubyCritic::Generator::HtmlReport
    - RubyCritic::Generator::Json::Simple
    - RubyCritic::Generator::JsonReport
    - RubyCritic::Generator::Text::List
    - RubyCritic::Reporter
    - RubyCritic::RevisionComparator
    - RubyCritic::Serializer
    - RubyCritic::SmellsStatusSetter
    - RubyCritic::SourceControlSystem::Base
    - RubyCritic::SourceControlSystem::Double
    - RubyCritic::SourceControlSystem::Git
    - RubyCritic::SourceControlSystem::Mercurial
    - RubyCritic::SourceLocator
    - RubyCritic
  Attribute:
    exclude:
    - RubyCritic::Analyser::Churn#source_control_system
    - RubyCritic::Configuration#deduplicate_symlinks
    - RubyCritic::Configuration#format
    - RubyCritic::Configuration#mode
    - RubyCritic::Configuration#no_browser
    - RubyCritic::Configuration#open_with
    - RubyCritic::Configuration#source_control_system
    - RubyCritic::Configuration#suppress_ratings
    - RubyCritic::Configuration#base_branch
    - RubyCritic::Configuration#base_branch_score
    - RubyCritic::Configuration#base_root_directory
    - RubyCritic::Configuration#compare_root_directory
    - RubyCritic::Configuration#feature_branch
    - RubyCritic::Configuration#feature_branch_score
    - RubyCritic::Configuration#feature_root_directory
    - RubyCritic::Configuration#threshold_score
    - RubyCritic::Configuration#base_branch_collection
    - RubyCritic::Configuration#feature_branch_collection
    - RubyCritic::RakeTask#name
    - RubyCritic::RakeTask#options
    - RubyCritic::RakeTask#paths
    - RubyCritic::RakeTask#verbose
  DuplicateMethodCall:
    exclude:
    - RubyCritic::Analyser::Churn#run
    - Parser::AST::Node#module_name
  TooManyStatements:
    exclude:
    - RubyCritic::RakeTask#initialize
    - RubyCritic::Analyser::Complexity#run
    - RubyCritic::Analyser::Coverage#synchronize_resultset
    - Parser::AST::Node#module_names
    - RubyCritic::Analyser::FlaySmells#run
    - RubyCritic::Cli::Application#execute
    - RubyCritic::Cli::Options::Argv#parse
    - RubyCritic::CommandFactory#self.command_class
    - RubyCritic::Configuration#set
    - RubyCritic::Generator::Html::CodeFile#render
    - RubyCritic::Reporter#self.report_generator_class
    - RubyCritic::SourceLocator#deduplicate_symlinks
    - RubyCritic::Command::Compare#compare_branches
  FeatureEnvy:
    exclude:
    - Parser::AST::Node#module_name
    - Parser::AST::Node#module_name
    - Parser::AST::Node#recursive_children
    - RubyCritic::Analyser::ReekSmells#add_smells_to
    - RubyCritic::Analyser::ReekSmells#create_smell
    - RubyCritic::ViewHelpers#smell_location_path
    - RubyCritic::Generator::HtmlReport#create_directories_and_files
    - RubyCritic::SourceLocator#deduplicate_symlinks
  NestedIterators:
    exclude:
    - Parser::AST::Node#recursive_children
    - RubyCritic::Analyser::FlaySmells#run
    - RubyCritic::Cli::Options::Argv#parse
    - RubyCritic::Generator::HtmlReport#create_directories_and_files
    - RubyCritic::AnalysedModulesCollection#initialize
  UtilityFunction:
    exclude:
    - RubyCritic::Analyser::Coverage#resultset_path
    - RubyCritic::Analyser::Coverage#resultset_writelock
    - RubyCritic::Analyser::FlaySmells#cost
    - RubyCritic::Analyser::FlaySmells#paths_to_analysed_modules
    - RubyCritic::Analyser::FlaySmells#smell_locations
    - RubyCritic::Analyser::FlogSmells#type
    - RubyCritic::Analyser::ReekSmells#smell_locations
    - RubyCritic::Cli::Application#print
    - RubyCritic::Cli::Options::File#value_for
    - RubyCritic::AnalysedModulesCollection#limited_cost_for
    - RubyCritic::Generator::Html::SimpleCovIndex#filtered
    - RubyCritic::Generator::Html::SimpleCovIndex#sorted
    - RubyCritic::Generator::Html::SmellsIndex#analysed_module_names
    - RubyCritic::Generator::HtmlReport#copy_assets_to_report_directory
    - RubyCritic::SourceControlSystem::Git#date_of_last_commit
    - RubyCritic::SourceControlSystem::Git#head_reference
    - RubyCritic::SourceControlSystem::Git#revisions_count
    - RubyCritic::SourceControlSystem::Git#stashes_count
    - RubyCritic::SourceControlSystem::Mercurial#date_of_last_commit
    - RubyCritic::SourceControlSystem::Mercurial#revisions_count
    - RubyCritic::ViewHelpers#code_index_path
    - RubyCritic::AnalysedModulesCollection#build_analysed_module
    - RubyCritic::Command::Compare#branch_directory
    - RubyCritic::Command::Compare#build_details
    - RubyCritic::Command::Compare#threshold_reached?
    - RubyCritic::Command::Compare#threshold_values_set?
  TooManyInstanceVariables:
    exclude:
    - RubyCritic::Generator::Html::CodeFile
    - RubyCritic::Generator::Html::Overview
    - RubyCritic::Generator::Html::SmellsIndex
  ControlParameter:
    exclude:
    - RubyCritic::CommandFactory#self.command_class
  UncommunicativeParameterName:
    exclude:
    - RubyCritic::AnalysedModule#to_json
    - RubyCritic::Location#to_json
    - RubyCritic::Rating#to_json
    - RubyCritic::Smell#to_json
    - Theon # This is needed for the tests to pass
  ClassVariable:
    exclude:
    - RubyCritic::SourceControlSystem::Base
  BooleanParameter:
    exclude:
    - RubyCritic::Config#self.respond_to_missing?
