# Offense count: 1
Metrics/AbcSize:
  Exclude:
    - 'lib/rubycritic/analysers/smells/flay.rb'
    - 'lib/rubycritic/cli/options.rb'

# Offense count: 2
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Exclude:
    - 'lib/rubycritic/analysers/smells/flay.rb'
    - 'lib/rubycritic/core/analysed_module.rb'

# Offense count: 1
Naming/AccessorMethodName:
  Exclude:
    - 'lib/rubycritic/generators/html/base.rb'

# Offense count: 1
Style/ClassVars:
  Exclude:
    - 'lib/rubycritic/source_control_systems/base.rb'

# Offense count: 1
Style/MethodMissing:
  Exclude:
    - 'lib/rubycritic/configuration.rb'

# Offense count: 3
Layout/IndentHeredoc:
  Enabled: false
